name: Run E2E Test
on:
  push:
    branches:
      - "feat/e2e_test"
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: |
          TAG=$(echo $GITHUB_SHA | cut -c1-5)
          IMAGE="cr-hn-1.bizflycloud.vn/e9cc3c5affc148fa84a2baeb42d8703d/ccm-test:$TAG"
          echo $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Check output
        run: |
          echo $IMAGE

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: cr-hn-1.bizflycloud.vn
          name: ${{ env.IMAGE }}
          username: ${{ secrets.ACCOUNT_EMAIL }}
          password: ${{ secrets.ACCOUNT_PASSWORD }}

  Run-e2e-test:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: actions/checkout@master

      - name: Set output
        id: vars
        run: |
          TAG=$(echo $GITHUB_SHA | cut -c1-5)
          IMAGE="cr-hn-1.bizflycloud.vn/e9cc3c5affc148fa84a2baeb42d8703d/ccm-test:$TAG"
          echo $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Check output
        run: |
          echo $IMAGE

      - name: Change directory to e2e
        run: cd e2e

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: |
          ./run.sh \
            -v ${{ secrets.VERSION_UID }} \
            -P ${{ secrets.VPC_ID }} \
            -u ${{ secrets.APP_CRED_ID }} \
            -p ${{ secrets.APP_CRED_SECRET }} \
            --email ${{ secrets.ACCOUNT_EMAIL }} \
            --password ${{ secrets.ACCOUNT_PASSWORD }} \
            --token ${{ secrets.SECRET_TOKEN }} \
            --image ${{ env.IMAGE }}
