name: Run E2E Test
on:
  workflow_run:
    workflows:
      - "Build-and-push-to-registry"
    types:
      - completed
jobs:
  Run-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: actions/checkout@master

      - name: Set output
        id: vars
        run: |
          TAG=$(echo $GITHUB_SHA | cut -c1-5)
          IMAGE="cr-hn-1.bizflycloud.vn/e9cc3c5affc148fa84a2baeb42d8703d/ccm-test:$TAG"
          echo $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Check output
        run: |
          echo $IMAGE

      - name: Run tests
        run: |
          cd e2e
          ls -la
          # ./run.sh \
          #   -P ${{ secrets.VPC_ID }} \
          #   -u ${{ secrets.APP_CRED_ID }} \
          #   -p ${{ secrets.APP_CRED_SECRET }} \
          #   --email ${{ secrets.ACCOUNT_EMAIL }} \
          #   --password ${{ secrets.ACCOUNT_PASSWORD }} \
          #   --token ${{ secrets.SECRET_TOKEN }} \
          #   --image ${{ env.IMAGE }}
