name: Run E2E Test
on:
  pull_request:
    types:
      - closed
    branches:
      - feat/dev
jobs:
  build_and_push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: |
          TAG=$(echo $GITHUB_SHA | cut -c1-5)
          IMAGE="${{ vars.IMAGE_PREFIX }}:$TAG"
          echo $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Check output
        run: |
          echo $IMAGE

  Run-e2e-test:
    if: github.event.pull_request.merged == true
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: actions/checkout@master

      - name: Set output
        id: vars
        run: |
          TAG=$(echo $GITHUB_SHA | cut -c1-5)
          IMAGE="${{ vars.IMAGE_PREFIX }}:$TAG"
          echo $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Check output
        run: |
          echo $IMAGE

      - name: Run tests
        run: |
          echo The PR was merged
