name: Run E2E Test
on:
  push:
    branches:
      - "feat/e2e_test"
jobs:
  get_vars:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set output
        run: echo ${{ vars.IMAGE_PREFIX }}
